// AUTO-GENERATED by `cargo run -p agentmix-types --features export --bin export-bindings`.
// Source of truth: src-tauri/crates/agentmix-types/src/lib.rs. Do not edit by hand.

// This file has been generated by Specta. Do not edit this file manually.
/**  Three-way scan classification (DESIGN.md §6.1). */
export type AssetCategory = 
/**  Spec-compliant and free of tool-specific fields. */
"portable" | 
/**  Spec-compliant but uses experimental / tool-specific fields. */
"tool-specific" | 
/**  Missing name/description, name/dir mismatch, or YAML parse failure. */
"invalid";

/**  Kinds of composable asset. v0.1 ships only `Skill`; new members extend later. */
export type AssetKind = "skill";

/**  A single deterministic health finding (no AI involved). */
export type HealthIssue = {
	level: HealthLevel,
	/**  Field the issue concerns, e.g. "name" or "description". */
	field: string,
	message: string,
	suggestion: string | null,
};

/**  Severity of a single deterministic health finding. */
export type HealthLevel = "warning" | "error";

/**  Overall deterministic health of an asset. */
export type HealthStatus = "ok" | "warning" | "error";

/**
 *  A Skill asset discovered by scanning — the concrete v0.1 provider of the
 *  Asset abstraction. The Asset-level fields (id, kind, identityKey,
 *  sourceProjectId, healthStatus, healthIssues) are flattened in here.
 */
export type Skill = {
	id: string,
	kind: AssetKind,
	/**  Unique within a scope; for a Skill this is its `name`. */
	identityKey: string,
	sourceProjectId: string,
	category: AssetCategory,
	healthStatus: HealthStatus,
	healthIssues: HealthIssue[],
	name: string,
	description: string,
	compatibility: string | null,
	metadata: { [key in string]: string } | null,
	skillDirPath: string,
	relativePathInProject: string,
	hasScripts: boolean,
	skillMdContent: string,
};

/**  A source project (folder) that was scanned for assets. */
export type SourceProject = {
	id: string,
	name: string,
	rootPath: string,
	isGitRepo: boolean,
	/**  ISO-8601 timestamp of when this project was first detected. */
	detectedAt: string,
	/**  ISO-8601 timestamp of the most recent update check, if any. */
	lastCheckedAt: string | null,
	skills: Skill[],
};
