// AUTO-GENERATED by `cargo run -p agentmix-types --features export --bin export-bindings`.
// Source of truth: src-tauri/crates/agentmix-types/src/lib.rs. Do not edit by hand.

// This file has been generated by Specta. Do not edit this file manually.
/**  Three-way scan classification (DESIGN.md §6.1). */
export type AssetCategory = 
/**  Spec-compliant and free of tool-specific fields. */
"portable" | 
/**  Spec-compliant but uses experimental / tool-specific fields. */
"tool-specific" | 
/**  Missing name/description, name/dir mismatch, or YAML parse failure. */
"invalid";

/**  Kinds of composable asset. v0.1 ships only `Skill`; new members extend later. */
export type AssetKind = "skill";

/**
 *  Where the pre-export backup archive will be written, and how big the content
 *  being backed up is. The archive itself is created by execute (T13), not here.
 */
export type BackupPlan = {
	/**  The target directory whose existing content is backed up before writes. */
	targetPath: string,
	/**  Destination archive: ~/.agentmix/backups/<project-hash>/<timestamp>.zip. */
	backupArchive: string,
	sizeBytes: number,
};

/**
 *  One asset competing for a name in the export target, fed to conflict
 *  detection. Kept asset-kind-agnostic: only the id and the name it would be
 *  written as matter, so the pipeline never branches on a concrete asset type.
 */
export type ConflictCandidate = {
	id: string,
	/**
	 *  The name this asset would be written as in the target directory
	 *  (a Skill's `name`, or its renamed value after conflict resolution).
	 */
	exportedName: string,
};

/**  Why an export conflict was raised (DESIGN.md §6.2). Both block export. */
export type ConflictKind = 
/**  Two or more selected assets share the same exported name. */
"nameCollision" | 
/**  A selected asset's exported name already exists in the target directory. */
"targetExists";

/**
 *  What execute actually did. Returned by ExportCoordinator.execute (T13) and
 *  shown in the UI; backupArchive (if any) backs the "open backup folder" action.
 */
export type ExecutionReport = {
	targetDir: string,
	skillsExported: number,
	filesCreated: number,
	filesOverwritten: number,
	backupArchive: string | null,
};

/**
 *  A v0.1 export conflict: assets that would collide on a name in the target
 *  directory (compared case-insensitively). Must be resolved before export.
 */
export type ExportConflict = {
	kind: ConflictKind,
	/**  The colliding exported name, as first encountered among the candidates. */
	exportedName: string,
	/**
	 *  Ids of the candidates that collide on this name. For NameCollision this
	 *  is the >= 2 selected assets; for TargetExists it is the single selected
	 *  asset whose name already exists at the target.
	 */
	assetIds: string[],
};

/**
 *  The single object the Dry-run preview renders and execute consumes
 *  (DESIGN.md §8.2). v0.1 targets one directory (Claude Code project-level), so
 *  the multi-target / runtime-warning fields are omitted until v0.2.
 */
export type ExportPlan = {
	/**  Resolved target directory: <project>/.claude/skills. */
	targetDir: string,
	operations: FileOperation[],
	/**  Must be empty before execute is allowed (DESIGN.md §8.2). */
	conflicts: ExportConflict[],
	backups: BackupPlan[],
	managedManifest: ManagedManifest,
	/**  Sum of all operation sizes — the total bytes the export will write. */
	totalBytes: number,
};

/**
 *  One selected asset to export: the source directory to copy and the name it
 *  will be written as. Asset-kind-agnostic — the planner copies directories and
 *  never inspects a concrete asset type.
 */
export type ExportRequestItem = {
	assetId: string,
	/**  Absolute path of the asset's source directory (a Skill's skillDirPath). */
	sourceDir: string,
	exportedName: string,
	/**  Source reference recorded in the manifest (e.g. sourceProjectId:relPath). */
	sourceRef: string,
};

/**
 *  One planned file write (DESIGN.md §8.2 FileOperation). Carries the source
 *  file path so execute copies exactly what the plan listed — preview and
 *  execution can't diverge (DoD-3). `sourcePath` extends the design model,
 *  which named only the asset; the path is needed for plan-driven execution.
 */
export type FileOperation = {
	kind: FileOperationKind,
	/**  Absolute destination path. */
	path: string,
	/**  Absolute source file path to copy from. */
	sourcePath: string,
	/**
	 *  Bytes that will be written. Equals the source size for verbatim files;
	 *  for the skill's SKILL.md it is the size after the `name:` rewrite.
	 *  Exported to TS as `number` (byte counts stay in JS's safe-integer range).
	 */
	size: number,
	/**  Id of the asset this operation belongs to. */
	sourceAsset: string,
};

/**
 *  A single file write planned for export. Produced only by the planner; never
 *  written by it. v0.1 produces Create / Overwrite (delete-on-reexport is a
 *  later reconciliation concern and is not modelled yet).
 */
export type FileOperationKind = "create" | "overwrite";

/**  A single deterministic health finding (no AI involved). */
export type HealthIssue = {
	level: HealthLevel,
	/**  Field the issue concerns, e.g. "name" or "description". */
	field: string,
	message: string,
	suggestion: string | null,
};

/**  Severity of a single deterministic health finding. */
export type HealthLevel = "warning" | "error";

/**  Overall deterministic health of an asset. */
export type HealthStatus = "ok" | "warning" | "error";

/**  One entry in the target-side ledger of AgentMix-managed assets. */
export type ManagedAsset = {
	name: string,
	/**  Where this asset came from (source project id + relative path). */
	sourceRef: string,
	/**  Content hash of the asset's SKILL.md, for later reconciliation. */
	contentHash: string,
};

/**  The target-side ledger written alongside the exported assets. */
export type ManagedManifest = {
	/**  e.g. <target>/.claude/skills/.agentmix-manifest.json. */
	manifestPath: string,
	managedAssets: ManagedAsset[],
};

/**
 *  A Skill asset discovered by scanning — the concrete v0.1 provider of the
 *  Asset abstraction. The Asset-level fields (id, kind, identityKey,
 *  sourceProjectId, healthStatus, healthIssues) are flattened in here.
 */
export type Skill = {
	id: string,
	kind: AssetKind,
	/**  Unique within a scope; for a Skill this is its `name`. */
	identityKey: string,
	sourceProjectId: string,
	category: AssetCategory,
	healthStatus: HealthStatus,
	healthIssues: HealthIssue[],
	name: string,
	description: string,
	compatibility: string | null,
	metadata: { [key in string]: string } | null,
	skillDirPath: string,
	relativePathInProject: string,
	hasScripts: boolean,
	skillMdContent: string,
};

/**  A source project (folder) that was scanned for assets. */
export type SourceProject = {
	id: string,
	name: string,
	rootPath: string,
	isGitRepo: boolean,
	/**  Timestamp (Unix epoch milliseconds, as a string) of when this project was scanned. */
	detectedAt: string,
	/**  Timestamp (Unix epoch milliseconds, as a string) of the most recent update check, if any. */
	lastCheckedAt: string | null,
	skills: Skill[],
};
