// AUTO-GENERATED by `cargo run -p agentmix-types --features export --bin export-bindings`.
// Source of truth: src-tauri/crates/agentmix-types/src/lib.rs. Do not edit by hand.

// This file has been generated by Specta. Do not edit this file manually.
/**  Three-way scan classification (DESIGN.md §6.1). */
export type AssetCategory = 
/**  Spec-compliant and free of tool-specific fields. */
"portable" | 
/**  Spec-compliant but uses experimental / tool-specific fields. */
"tool-specific" | 
/**  Missing name/description, name/dir mismatch, or YAML parse failure. */
"invalid";

/**  Kinds of composable asset. v0.1 ships only `Skill`; new members extend later. */
export type AssetKind = "skill";

/**
 *  One asset competing for a name in the export target, fed to conflict
 *  detection. Kept asset-kind-agnostic: only the id and the name it would be
 *  written as matter, so the pipeline never branches on a concrete asset type.
 */
export type ConflictCandidate = {
	id: string,
	/**
	 *  The name this asset would be written as in the target directory
	 *  (a Skill's `name`, or its renamed value after conflict resolution).
	 */
	exportedName: string,
};

/**
 *  A v0.1 export conflict: two or more selected assets would be written to the
 *  same target directory under the same name (compared case-insensitively).
 *  Must be resolved before export (DESIGN.md §6.2).
 */
export type ExportConflict = {
	/**  The colliding exported name, as first encountered among the candidates. */
	exportedName: string,
	/**  Ids of the candidates that collide on this name (length >= 2). */
	assetIds: string[],
};

/**  A single deterministic health finding (no AI involved). */
export type HealthIssue = {
	level: HealthLevel,
	/**  Field the issue concerns, e.g. "name" or "description". */
	field: string,
	message: string,
	suggestion: string | null,
};

/**  Severity of a single deterministic health finding. */
export type HealthLevel = "warning" | "error";

/**  Overall deterministic health of an asset. */
export type HealthStatus = "ok" | "warning" | "error";

/**
 *  A Skill asset discovered by scanning — the concrete v0.1 provider of the
 *  Asset abstraction. The Asset-level fields (id, kind, identityKey,
 *  sourceProjectId, healthStatus, healthIssues) are flattened in here.
 */
export type Skill = {
	id: string,
	kind: AssetKind,
	/**  Unique within a scope; for a Skill this is its `name`. */
	identityKey: string,
	sourceProjectId: string,
	category: AssetCategory,
	healthStatus: HealthStatus,
	healthIssues: HealthIssue[],
	name: string,
	description: string,
	compatibility: string | null,
	metadata: { [key in string]: string } | null,
	skillDirPath: string,
	relativePathInProject: string,
	hasScripts: boolean,
	skillMdContent: string,
};

/**  A source project (folder) that was scanned for assets. */
export type SourceProject = {
	id: string,
	name: string,
	rootPath: string,
	isGitRepo: boolean,
	/**  Timestamp (Unix epoch milliseconds, as a string) of when this project was scanned. */
	detectedAt: string,
	/**  Timestamp (Unix epoch milliseconds, as a string) of the most recent update check, if any. */
	lastCheckedAt: string | null,
	skills: Skill[],
};
